# python:3.11.1の公式 image をベースの image として設定
FROM python:3.11.1

# 作業ディレクトリの作成
RUN mkdir /code

# 作業ディレクトリの設定
WORKDIR /code

# カレントディレクトリにある資産をコンテナ上の指定のディレクトリにコピーする
COPY . /code

RUN chmod -R 777 /code

# pipでrequirements.txtに指定されているパッケージを追加する
RUN pip install --upgrade pip && pip install -r requirements.txt