version: '3.7'

services:
  web:
    build:
      context: ./seatbooking
      dockerfile: Dockerfile.prod

    # シェルファイルを実行する
    command: sh -c "/code/entrypoint.sh"

    # 名前付きボリューム
    # [ボリューム名]：[コンテナ内絶対パス]
    # python manage.py collectstaticコマンドで、staticファイルが集約される
    volumes:
      - static_volume:/code/static
    
    # ほかのコンテナから8000番ポートでアクセスさせる
    expose:
      - 8000

    env_file:
      - ./.env.prod
  
  nginx:
    build:
      context: ./nginx
      dockerfile: /Dockerfile.prod

    # 名前付きボリューム
    # [ボリューム名]：[コンテナ内絶対パス]
    # python manage.py collectstaticコマンドで、staticファイルが集約される
    # staticファイルの表示はnginxが行う
    volumes:
      - static_volume:/static
    ports:
        - 50001:80
    depends_on:
        - web 

# 名前付きボリュームの設定
# 設定値がない場合でも必要
volumes:
  static_volume: